name: Generate Snake and Update WakaTime

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *'  # Runs at 12 AM UTC every day

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake for Dark Mode
        uses: Platane/snk@master
        with:
          github_user_name: machinelearningprodigy
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif

      - name: Generate Snake for Light Mode
        uses: Platane/snk@master
        with:
          github_user_name: machinelearningprodigy
          outputs: |
            dist/github-snake.svg?color_snake=darkgreen&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 30
          REPOSITORY: machinelearningprodigy/machinelearningprodigy
